name: gps_history
description: Module intended to represent histories of GPS points.
version: 0.0.2
homepage: https://github.com/anxix/gps_history

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
