name: gps_history
description: >
  Represents histories of GPS points. Handles millions of points quickly
  and using relatively little memory. Can import Google location history JSON
  files.

version: 0.0.8
repository: https://github.com/anxix/gps_history

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  path: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.4
