name: gps_history
description: >
  Represents histories of GPS points. Handles millions of points quickly
  and using relatively little memory. Can import Google location history JSON
  files.

version: 0.0.3
repository: https://github.com/anxix/gps_history

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
