name: google_json_to_sqlite
description: A sample application for converting Google location history JSON to SQLite.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.2
  gps_history: ^0.0.5
  sqflite_common: ^2.2.1+1
  sqflite_common_ffi: ^2.1.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
